### ISSUE TITLE
Beta Launch (!) Todo's

### ISSUE THREAD

**Issue by AndreasInk** [Highschool-iOS-Devs/Studeo#5]
<h1>Beta Launch Preparation Items</h1>

- [x] Fully connect leaderboard UI to Firebase 

- [x] Fully connect profile image UI to Firebase @AndreasInk 

- [x] Fully connect home UI to Firebase 

- [x] Develop leaderboard ranking system

- [x] Test app on iPhone 11 Max @DakshinD

- [x] Test app on iPhone SE @DakshinD

- [x] Test app on iPad Pro 12.9 @DakshinD

- [x] Double check pairing functionality

- [x] Animoji Chat @AndreasInk 

- [x] Setup Instagram @AndreasInk  

- [x] Setup Linkedin 

- [x] Setup Twitter

**Comment by jevonmao** [comment]
- [ ] Double check pairing functionality
- [ ] Fully connect home UI to Firebase 

(@jevonmao, Nov 25, ETA: 1~2 weeks)

**Comment by DakshinD** [comment]
- [ ] Test app on iPhone 11 Max
- [ ] Test app on iPhone SE
- [ ] Test app on iPad Pro 12.9

(@DakshinD)
